logging:
  level:
    sql: debug

springdoc:
  swagger-ui:
    path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/chargestation"
    username: user
    password: welcome
  liquibase:
    change-log: classpath:/db/changelog/master.yml
    contexts: test

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: off

app:
  elastic:
    index: on
  security:
    randSeed: cafebabe
  props:
    version:
      apiVersion: 1
      appVersion: 0.0.1-SNAPSHOT
    patterns:
      - "yyyy-MM-dd'T'HH:mm:ssZ"
      - 'EEE, d MMM yyyy'
      - 'dd-MM-yyyy'
      - 'dd.MM.yyyy HH:mm:ss'
      - 'dd.MM.yyyy'
      - 'yyyy/MM/dd'
      - 'yyyy-MM-dd'
      - 'yyyy.MM.dd'
      - 'yyyy/MM/dd HH:mm'
      - 'yyyy-MM-dd HH:mm'
      - 'yyyy.MM.dd HH:mm'
